app:
  id: pipal-server
spring:
  profiles:
    active: online
  application:
    name: pipal-server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_pipal
    username: pipal
    password:
  data:
    redis:
      repositories:
        enable: false
    elasticsearch:
      repositories:
        enable: false
service:
  config:
    token: a441f74b523c41e197340c6277c0123f